server.port=8082
spring.application.name=driver-service
spring.data.mongodb.uri=${MONGO_URI}

# Swagger / OpenAPI config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
