spring.application.name=account-service
server.port=${PORT:8081}
spring.data.mongodb.uri=mongodb+srv://admin:Fami123Kali@cluster0.97z98fd.mongodb.net/ridelink?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Ridelink
spring.data.mongodb.auto-index-creation=true
security.jwt.secret=${JWT_SECRET:dev-only-change-this-secret-before-deployment-please-keep-it-long-enough}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}
logging.level.org.springframework.data.mongodb=DEBUG