spring.application.name=ride-service
server.port=${SERVER_PORT:8083}
spring.mongodb.uri=${MONGODB_URI}
spring.cloud.compatibility-verifier.enabled=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html