spring.application.name=ride-service
server.port=${SERVER_PORT:8083}
spring.data.mongodb.uri=${MONGO_DB_URI:mongodb://localhost:27017/ridelink}
driver.service.url=${DRIVER_SERVICE_URL:http://localhost:8082}
spring.cloud.compatibility-verifier.enabled=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
